name: Deployment

"on":
  - push
  - pull_request

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: echo $GITHUB_SHA >> public/index.html
      - uses: .github/actions/
        env:
          BUILD_DIR: build/
          GH_PAT: ${{ secrets.GH_PAT }}
